group_to_elems = {
    1: ["H", "Li", "Na", "K", "Rb", "Cs"],
    2: ["Be", "Mg", "Ca", "Sr", "Ba"],
    3: ["Sc", "Y"],
    4: ["Ti", "Zr", "Hf"],
    5: ["V", "Nb", "Ta"],
    6: ["Cr", "Mo", "W"],
    7: ["Mn", "Tc", "Re"],
    8: ["Fe", "Ru", "Os"],
    9: ["Co", "Rh", "Ir"],
    10: ["Ni", "Pd", "Pt"],
    11: ["Cu", "Ag", "Au"],
    12: ["Zn", "Cd", "Hg"],
    13: ["B", "Al", "Ga", "In", "Tl"],
    14: ["C", "Si", "Ge", "Sn", "Pb"],
    15: ["N", "P", "As", "Sb", "Bi"],
    16: ["O", "S", "Se", "Te"],
    17: ["F", "Cl", "Br", "I"],
    18: ["He", "Ne", "Ar", "Kr", "Xe"],
}
row_to_elems = {
    1: ["H", "He"],
    2: ["Li", "Be", "B", "C", "N", "O", "F", "Ne"],
    3: ["Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar"],
    4: [
        "K",
        "Ca",
        "Sc",
        "Ti",
        "V",
        "Cr",
        "Mn",
        "Fe",
        "Co",
        "Ni",
        "Cu",
        "Zn",
        "Ga",
        "Ge",
        "As",
        "Se",
        "Br",
        "Kr",
    ],
    5: [
        "Rb",
        "Sr",
        "Y",
        "Zr",
        "Nb",
        "Mo",
        "Tc",
        "Ru",
        "Rh",
        "Pd",
        "Ag",
        "Cd",
        "In",
        "Sn",
        "Sb",
        "Te",
        "I",
        "Xe",
    ],
    6: [
        "Cs",
        "Ba",
        "Hf",
        "Ta",
        "W",
        "Re",
        "Os",
        "Ir",
        "Pt",
        "Au",
        "Hg",
        "Tl",
        "Pb",
        "Bi",
    ],
    # 7: [
    #     "Rf",
    #     "Db",
    #     "Sg",
    #     "Bh",
    #     "Hs",
    #     "Mt",
    #     "Ds",
    #     "Rg",
    #     "Cn",
    #     "Nh",
    #     "Fl",
    #     "Mc",
    #     "Lv",
    #     "Ts",
    #     "Og",
    # ],
}
# Here we treat actinoids and lanthanoids as a single group
# We except the elements that are not included in training data
actinoide = [
    "Th",
    "Pa",
    "U",
    "Np",
    "Pu",
    # "Am",
    # "Cm",
    # "Bk",
    # "Cf",
    # "Es",
    # "Fm",
    # "Md",
    # "No",
    # "Lr",
]
lanthanoid = [
    "La",
    "Ce",
    "Pr",
    "Nd",
    "Pm",
    "Sm",
    "Eu",
    "Gd",
    "Tb",
    "Dy",
    "Ho",
    "Er",
    "Tm",
    "Yb",
    "Lu",
]
