train:
  random_seed: 0
  patience: 10

wandb:
  online: true
  exp_name: contriever
  project: matagent

outputs:
  dir: .

optim:
  optimizer:
    type: adam
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1e-08
    weight_decay: 0.0
  lr_scheduler:
    type: plateau
    factor: 0.8
    patience: 5
    min_lr: 1e-4
  epochs: 100
  temperature: 0.7
  base_model: t5-base

data:
  root_path: ../../../data/mp_20
  # data_path: ../preprocess
  attributes: ["formation_energy_per_atom", "band_gap", "e_above_hull", "elements"]
  batch_size: 128
